# Adds namespace to all resources.
namespace: OPENSHIFT-NAMESPACE

resources:
- ../../../../../config/base/crd
- ../../../../../config/base/rbac
- ../../../../../config/base/manager

patches:
- target:
    kind: Service
    name: catalogserver
  path: patches/manager_service.yaml
- target:
    kind: Service
    name: catalogserver
  path: patches/catalogserver_service_port.yaml
- target:
    kind: MutatingWebhookConfiguration
    name: mutating-webhook-configuration
  path: patches/mutating_webhook_config.yaml
- target:
    kind: Deployment
    name: controller-manager
  path: patches/manager_deployment_certs.yaml
